GET http://localhost:5000/api/character/brucelee

###
POST http://localhost:5000/api/chat
Content-Type: application/json

{
    "query": "what is your email address?",
}


###
GET http://localhost:5000/api/quiz